### ISSUE TITLE
AngularJS renders too slowly or not at all without $scope.$apply in cs-wizard

### ISSUE THREAD

**Issue by kdaveed** [cloudstorm/cloudstorm#108]
The task is to figure out what AngularJS does in the 2-3 seconds between the end of the execution of our code and the html rendering.

**Comment by kdaveed** [comment]
The problem can be found on the branch unLoadRouter and from the commit 6439eab6691a6b59d5b9757cfbf2f7dc42c9dfac, under the link http://localhost:8000/sample.html#!/planets/37

**Comment by kdaveed** [comment]
The time is lost between the csWizard and csWizardPanel.

**Comment by qqbenq** [comment]
Please merge the latest master into your branch, as it contains a modification that removes the unnecessary scope.apply()

**Comment by kdaveed** [comment]
If instantly the url (i.e.  http://localhost:8000/sample.html#!/planets/37) is called, then the form is loaded, but if a link is clicked on the index page then the form is not loaded. 
Log:
* [15.51 s] csWizard singlePage branch
* [0.108 s] csWizard finish

And the application loads neither the csWizardPanel, nor the csForm.
